#指定运行环境
language: node_js
#指定nodejs版本，可以指定多个
node_js:
  - 8.6.0

install:
  - npm install -g codecov
  - npm install --save-dev mocha
#运行的脚本命令
script:
  - istanbul cover ./node_modules/mocha/bin/_mocha --reporter lcovonly -- -R spec
  - codecov
  - npm run build
#指定分支，只有指定的分支提交时才会运行脚本
branches:
  only:
    - master
